---
title: "Virome - ERR2 group"
author: "AL,AM, PSR, DP"
date: "3/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Importing libraries for data manipulation:
```{r}
library(tidyverse)
library(lubridate)
library(here)
library(readr)
library(dbplyr)
```


#Importing dataset from .csv fail
```{r}
dataset <- dataset <- read_csv("data/phage_counts.csv")
dataset
```

```{r}
filter(dataset, timepoint == "0")
```

```{r}
graph_1 <- dataset %>% 
    group_by(., tax_id) %>% 
    arrange(tax_id) %>% 
    count(tax_id)
graph_1
```

```{r}
graph_1 %>% 
    ggplot(aes(x = tax_id, y = n)) +
    geom_point(aes(color = tax_id))
```


```{r}
graph_1 %>% 
    ggplot(aes(x = tax_id, y = n)) +
    geom_point(aes(color = tax_id)) +
    scale_y_log10()
```
```{r}
sub <- dataset %>% select(subject) %>% count(subject)
sub
```

```{r}
ravi <- dataset %>% select(subject, arm, timepoint) %>% filter(arm == "M") %>%   count(arm, subject, timepoint)
ravi
placebo <- dataset %>% select(subject, arm, timepoint) %>% filter(arm == "P") %>%   count(arm, subject, timepoint)
placebo
```

```{r}
ggplot() +
    geom_point(data = ravi, aes(x = subject,y = n, color = timepoint)) +
    geom_point(data = placebo, aes(x = subject,y = n, color = timepoint), shape = 3)
```


```{r}
subOP <- dataset %>% 
    filter(timepoint == "0") %>% 
    filter( arm == "P") %>% 
    arrange(tax_id)
csubOP <- count(subOP, tax_id)
csubOP

sub2P <- dataset %>% 
    filter(timepoint == "2") %>% 
    filter( arm == "P") %>% 
    arrange(tax_id)
csub2P <-count(sub2P, tax_id)
csub2P

sub4P <- dataset %>% 
    filter(timepoint == "4") %>% 
    filter( arm == "P") %>% 
    arrange(tax_id)
csub4P <- count(sub4P, tax_id)
csub4P
```

```{r}
ggplot()+
    geom_point(data = csubOP, aes(x = tax_id, y = n), color = "blue") +
    geom_point(data = csub2P, aes(x = tax_id, y = n), color = "green") +
    geom_point(data = csub4P, aes(x = tax_id, y = n ), color = "red" ) +
    scale_y_log10()
```

```{r}
subOM <- dataset %>% 
    filter(timepoint == "0") %>% 
    filter( arm == "M") %>% 
    arrange(tax_id)
csubOM <- count(subOM, tax_id)
csubOM

sub2M <- dataset %>% 
    filter(timepoint == "2") %>% 
    filter( arm == "M") %>% 
    arrange(tax_id)
csub2M <-count(sub2M, tax_id)
csub2M

sub4M <- dataset %>% 
    filter(timepoint == "4") %>% 
    filter( arm == "M") %>% 
    arrange(tax_id)
csub4M <- count(sub4M, tax_id)
csub4M
```

```{r}
ggplot()+
    geom_point(data = csubOP, aes(x = tax_id, y = n), color = "blue") +
    geom_point(data = csub2P, aes(x = tax_id, y = n), color = "green") +
    geom_point(data = csub4P, aes(x = tax_id, y = n ), color = "red" ) +
    scale_y_log10()
```


